language: generic
sudo: false
env:
  matrix:
    - BUILDOUT_TARGET=python27 EXECUTABLE=python-2.7/bin/python
os:
  - linux
  - osx
script:
  - make -f make-tests buildout_target=$BUILDOUT_TARGET
  - $EXECUTABLE -V